import { NgModule } from '@angular/core';
import { MatButtonModule,
         MatButtonToggleModule, 
         MatIconModule, 
         MatBadgeModule,
         MatProgressSpinnerModule,
         MatProgressBarModule,
         MatToolbarModule,
         MatSidenavModule,
         MatMenuModule,
         MatListModule,
         MatDividerModule,
         MatGridListModule,
         MatExpansionModule,
         MatFormFieldModule,
         MatCardModule,
         MatTabsModule,
         MatStepperModule,
         MatInputModule,
         MatSelectModule,
         MatAutocompleteModule,
         MatCheckboxModule,
         MatRadioModule,
         MatNativeDateModule,
         MatDatepickerModule,
         MatTooltipModule,
         MatSnackBarModule,
         MatDialogModule,
          
        } from '@angular/material';

const Material = [
  MatButtonModule,
  MatButtonToggleModule,
  MatIconModule,
  MatBadgeModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatToolbarModule,
  MatSidenavModule,
  MatMenuModule,
  MatListModule,
  MatDividerModule,
  MatGridListModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatCardModule,
  MatTabsModule,
  MatStepperModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatAutocompleteModule,
  MatCheckboxModule,
  MatRadioModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTooltipModule,
  MatSnackBarModule,
  MatDialogModule,
]

@NgModule({
  declarations: [],
  imports: [Material],
  exports: [Material]
})
export class MaterialModule { }
